# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://dpg-d715iqn5r7bs73dl19eg-a.singapore-postgres.render.com/moneymanger_heqn
spring.datasource.username=${pos-sql-username}
spring.datasource.password=${pos-sql-password}
