spring.application.name=moneytracker

# DATABASE
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# SERVER
server.port=${PORT:8080}
server.address=0.0.0.0

# EMAIL
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${BREVO_LOGIN}
spring.mail.password=${SMTP_KEY}
app.mail.from=${T_EMAIL}

# JWT
jwt.secret=${JWT_SECRET}

# FRONTEND
money.manager.frontend.url=${FRONTEND_URL}

# ACTIVATION
backendapp.activation.url=${BACKEND_URL}
